In [1]:
import pandas as pd
import numpy as np
import scipy.optimize as opt
import time

In [2]:
# Reading the data on python
ps3_data = pd.read_stata('PS3_data.dta')
ps3_data.head(n=5)

id68  year  intid relhh  hannhrs  wannhrs  hlabinc  wlabinc  nochild  \
0     1  1967      1  Head   1200.0   2000.0      NaN      NaN        0   
1     2  1967      2  Head      0.0      0.0      NaN      NaN        0   
2     3  1967      3  Head      0.0      0.0      NaN      NaN        0   
3     4  1967      4  Head   1560.0      0.0      NaN      NaN        6   
4     5  1967      5  Head   2500.0   2000.0      NaN      NaN        3   

   wrace ...   redpregovinc  hsex  wsex   age  wage  hpersno  wpersno  hyrsed  \
0    NaN ...         5614.0   1.0   2.0  52.0  46.0      1.0      2.0     8.0   
1    NaN ...            0.0   1.0   2.0  56.0  57.0      1.0      2.0     3.0   
2    NaN ...            0.0   1.0   2.0  77.0  64.0      1.0      2.0     NaN   
3    1.0 ...         3280.0   1.0   2.0  45.0  44.0      1.0      2.0     8.0   
4    1.0 ...         7900.0   1.0   2.0  24.0  22.0      1.0      2.0    10.0   

   wyrsed  pce  
0     8.0  0.0  
1     3.0  0.0  
2     3.0  0.0  
3     5.0  0.0  
4     9.0  0.0  

[5 rows x 52 columns]

# Data Cleaning and creation of necessary variables

In [3]:
# Deleting cell with hannhrs=0
ps3_data=ps3_data[ps3_data.hannhrs !=0]

In [4]:
# Creating a new variable for wage per hour = wph

ps3_data['wph']=ps3_data.hlabinc / ps3_data.hannhrs

# drop if missing value for the wph
ps3_data = ps3_data[ps3_data.wph.isnull() != True ]

# Natural logarithm conversion of a variable

ps3_data['lnwage']=np.log(ps3_data.wph)

In [5]:
# Creating a variable for constant

ps3_data['const']=1

In [6]:
# Creating dummy variables for all cateries given for a categorical variable

race = pd.get_dummies(ps3_data['hrace'])

In [7]:
ps3_data = pd.concat([ps3_data, race], axis=1)
ps3_data

id68  year  intid relhh  hannhrs  wannhrs        hlabinc  \
11161    402  1971      1  Head   1523.0      0.0   62928.707031   
11162    446  1971      2  Head    520.0      0.0    1618.640747   
11164    461  1971      4  Head   2010.0      0.0   22660.970703   
11165    462  1971      5  Head   1960.0      0.0   12949.125977   
11166   1126  1971      8  Head   2860.0      0.0   29337.865234   
11167   1585  1971     10  Head    840.0    833.0    8627.355469   
11170     97  1971     15  Head   1960.0      0.0   19678.625000   
11171    237  1971     16  Head    604.0      0.0    2124.466064   
11172    669  1971     17  Head    683.0      0.0    3439.611816   
11173    284  1971     20  Head   2400.0      0.0   76885.437500   
11174   2562  1971     25  Head   1945.0      0.0   43492.878906   
11175     50  1971     29  Head   3164.0   2000.0   31968.156250   
11177   1348  1971     31  Head    120.0      0.0    1618.640747   
11178   1032  1971     32  Head    900.0      0.0   34396.117188   
11180    255  1971     34  Head     30.0      0.0     404.660187   
11186      1  1971     45  Head   2000.0      0.0   18590.089844   
11188     98  1971     47  Head   1976.0      0.0   20103.519531   
11190    591  1971     49  Head    120.0   1680.0    1254.446655   
11191    592  1971     50  Head   1600.0      0.0   24785.437500   
11192   1064  1971     56  Head    980.0     72.0   18614.369141   
11196   1679  1971     61  Head   2652.0   1960.0   25461.220703   
11198   1415  1971     63  Head   2416.0      0.0   39980.429688   
11199    280  1971     64  Head   3427.0   1040.0   56611.960938   
11201    601  1971     66  Head     40.0      0.0     121.398064   
11202   1360  1971     67  Head   2500.0   1760.0   50582.523438   
11204    721  1971     69  Head     40.0      0.0     226.609711   
11205    752  1971     70  Head   3060.0      0.0    2610.058350   
11206    973  1971     71  Head   2450.0      0.0   25190.097656   
11207   1492  1971     72  Head   2425.0   1720.0   28407.146484   
11208   2067  1971     74  Head    520.0      0.0    1618.640747   
...      ...   ...    ...   ...      ...      ...            ...   
123753  1830  2002   7799  Head   2200.0   1800.0   36422.121094   
123754  1312  2002   7801  Head    810.0   2450.0   19202.431641   
123755  1012  2002   7803  Head   2189.0   1887.0   59266.761719   
123756   664  2002   7804  Head   1584.0      0.0   10236.986328   
123757  1787  2002   7807  Head   1954.0   1560.0   49568.566406   
123758   245  2002   7809  Head    696.0   2156.0   32327.326172   
123759  2108  2002   7810  Head   2232.0      0.0   19396.394531   
123760  2530  2002   7811  Head   2080.0      0.0   19396.394531   
123761  2246  2002   7813  Head   2012.0   1359.0   96981.976562   
123763  1722  2002   7819  Head   2016.0      0.0   26939.437500   
123764   677  2002   7822  Head   1212.0   2072.0   32327.326172   
123765   840  2002   7823  Head   2056.0      0.0   25861.861328   
123766   840  2002   7824  Head   2461.0      0.0   20473.972656   
123767  2704  2002   7826  Head   2178.0   2760.0   53878.875000   
123768   498  2002   7827  Head   1818.0      0.0   40947.945312   
123769   391  2002   7828  Head   1800.0      0.0   21551.550781   
123770  2509  2002   7836  Head   2340.0      0.0   42564.312500   
123771  1060  2002   7837  Head   1050.0   2080.0   11314.563477   
123772   514  2002   7842  Head   2285.0   1904.0   63577.074219   
123774   729  2002   7845  Head   2244.0      0.0   18318.818359   
123775  1016  2002   7847  Head     16.0      0.0    4310.310059   
123776  1141  2002   7849  Head     12.0      0.0     107.757751   
123777  2678  2002   7850  Head   2080.0      0.0   34482.480469   
123778   961  2002   7855  Head   2070.0      0.0   16163.663086   
123779  2228  2002   7856  Head   2178.0      0.0  122843.835938   
123780   826  2002   7857  Head   2064.0      0.0   86206.203125   
123781  2067  2002   7862  Head   2088.0      0.0   25861.861328

In [8]:
# At this point category 8.0 got dropped and there is no Hispanic people in the sample. So, I don't have the variable 'Hispanic' in my model.
# Renaming the existing variables in the dataframe

ps3_data.rename (columns = {'hyrsed':'educ',1.0:'White',2.0:'Black',3.0:'Native_American',},inplace=True)

In [9]:
ps3_data.rename(columns={'Native_American':'Other_Race'}, inplace=True)

In [10]:
ps3_data.describe()

id68          year         intid       hannhrs       wannhrs  \
count  90041.000000  90041.000000  90041.000000  90041.000000  90041.000000   
mean    1510.727402   1986.337879   3518.940594   2072.334961    767.537964   
std      835.012733      8.821313   2313.991695    750.543823    915.022034   
min        1.000000   1971.000000      1.000000      1.000000      0.000000   
25%      783.000000   1979.000000   1677.000000   1805.000000      0.000000   
50%     1541.000000   1986.000000   3326.000000   2065.000000     81.699997   
75%     2240.000000   1994.000000   5062.000000   2456.000000   1710.000000   
max     2930.000000   2002.000000  16968.000000   7800.000000   5840.000000   

            hlabinc        wlabinc       nochild         wrace         hrace  \
count  9.004100e+04   45673.000000  90041.000000  74042.000000  89923.000000   
mean   4.217924e+04   21973.662109      0.951544      1.097256      1.124495   
std    4.672406e+04   20506.021484      1.168194      0.355753      0.392191   
min    6.353981e-01       1.192780      0.000000      1.000000      1.000000   
25%    1.991069e+04    8078.967285      0.000000      1.000000      1.000000   
50%    3.465334e+04   18154.320312      0.000000      1.000000      1.000000   
75%    5.273935e+04   30256.060547      2.000000      1.000000      1.000000   
max    3.771521e+06  417271.468750     11.000000      8.000000      3.000000   

           ...            wpersno          educ        wyrsed           pce  \
count      ...       63091.000000  89537.000000  62617.000000  90041.000000   
mean       ...          65.339951     13.230185     13.031749      0.610144   
std        ...          80.976387      2.525720      2.228436      0.209193   
min        ...           1.000000      1.000000      1.000000      0.247121   
25%        ...           2.000000     12.000000     12.000000      0.421747   
50%        ...           4.000000     12.000000     12.000000      0.614522   
75%        ...         170.000000     16.000000     15.000000      0.803488   
max        ...         231.000000     17.000000     17.000000      0.928007   

                wph        lnwage    const         White         Black  \
count  90041.000000  90041.000000  90041.0  90041.000000  90041.000000   
mean      20.659475      2.751247      1.0      0.896736      0.079575   
std       24.797258      0.768539      0.0      0.304305      0.270635   
min        0.000204     -8.499092      1.0      0.000000      0.000000   
25%       10.415504      2.343295      1.0      1.000000      0.000000   
50%       16.558668      2.806910      1.0      1.000000      0.000000   
75%       24.736206      3.208268      1.0      1.000000      0.000000   
max     1865.037964      7.531037      1.0      1.000000      1.000000   

         Other_Race  
count  90041.000000  
mean       0.022379  
std        0.147913  
min        0.000000  
25%        0.000000  
50%        0.000000  
75%        0.000000  
max        1.000000  

[8 rows x 57 columns]

In [11]:
# Creating a subset of the dataset incorporating necessary variables

ps3_data1=ps3_data[['year','hsex','age','educ','wph','White','Black','Other_Race','lnwage','const']]
ps3_data1

year  hsex   age  educ         wph  White  Black  Other_Race  \
11161   1971   1.0  51.0  12.0   41.318916      1      0           0   
11162   1971   2.0  62.0  17.0    3.112771      1      0           0   
11164   1971   1.0  55.0   5.0   11.274115      1      0           0   
11165   1971   1.0  59.0   5.0    6.606697      1      0           0   
11166   1971   1.0  25.0  16.0   10.257995      1      0           0   
11167   1971   1.0  67.0  12.0   10.270661      1      0           0   
11170   1971   1.0  63.0   6.0   10.040114      1      0           0   
11171   1971   2.0  65.0   8.0    3.517328      1      0           0   
11172   1971   2.0  66.0  12.0    5.036035      1      0           0   
11173   1971   1.0  39.0  16.0   32.035599      1      0           0   
11174   1971   2.0  58.0  12.0   22.361378      1      0           0   
11175   1971   1.0  36.0  12.0   10.103716      1      0           0   
11177   1971   2.0  72.0   8.0   13.488673      1      0           0   
11178   1971   1.0  66.0   9.0   38.217907      1      0           0   
11180   1971   2.0  67.0  16.0   13.488673      1      0           0   
11186   1971   2.0  50.0   8.0    9.295045      1      0           0   
11188   1971   2.0  24.0  14.0   10.173846      1      0           0   
11190   1971   1.0  71.0   8.0   10.453722      1      0           0   
11191   1971   1.0  62.0   8.0   15.490898      1      0           0   
11192   1971   1.0  31.0  17.0   18.994255      1      0           0   
11196   1971   1.0  42.0  11.0    9.600762      0      1           0   
11198   1971   1.0  36.0  11.0   16.548191      1      0           0   
11199   1971   1.0  44.0   9.0   16.519394      1      0           0   
11201   1971   1.0  84.0   8.0    3.034952      1      0           0   
11202   1971   1.0  55.0   7.0   20.233009      1      0           0   
11204   1971   2.0  70.0   6.0    5.665243      0      1           0   
11205   1971   2.0  59.0   7.0    0.852960      1      0           0   
11206   1971   1.0  52.0  11.0   10.281672      1      0           0   
11207   1971   1.0  63.0  14.0   11.714287      1      0           0   
11208   1971   2.0  46.0   8.0    3.112771      1      0           0   
...      ...   ...   ...   ...         ...    ...    ...         ...   
123753  2002   1.0  42.0  11.0   16.555510      1      0           0   
123754  2002   1.0  43.0  14.0   23.706705      0      1           0   
123755  2002   1.0  31.0  12.0   27.074812      1      0           0   
123756  2002   2.0  43.0  12.0    6.462744      1      0           0   
123757  2002   1.0  41.0  16.0   25.367741      0      1           0   
123758  2002   1.0  28.0  14.0   46.447308      0      1           0   
123759  2002   2.0  46.0  12.0    8.690141      1      0           0   
123760  2002   2.0  37.0  12.0    9.325190      1      0           0   
123761  2002   1.0  53.0  16.0   48.201778      1      0           0   
123763  2002   2.0  26.0  15.0   13.362816      0      1           0   
123764  2002   1.0  21.0  12.0   26.672710      1      0           0   
123765  2002   1.0  49.0  12.0   12.578727      0      1           0   
123766  2002   1.0  29.0  13.0    8.319371      0      1           0   
123767  2002   1.0  40.0  12.0   24.737776      1      0           0   
123768  2002   2.0  53.0  12.0   22.523623      1      0           0   
123769  2002   1.0  24.0  16.0   11.973083      1      0           0   
123770  2002   2.0  25.0  16.0   18.189877      1      0           0   
123771  2002   1.0  22.0  12.0   10.775775      1      0           0   
123772  2002   1.0  56.0  14.0   27.823666      0      1           0   
123774  2002   2.0  20.0  12.0    8.163466      1      0           0   
123775  2002   1.0  36.0  16.0  269.394379      1      0           0   
123776  2002   2.0  25.0  10.0    8.979813      1      0           0   
123777  2002   1.0  51.0  12.0   16.578115      1      0           0   
123778  2002   2.0  22.0  12.0    7.808533      

In [12]:
# Sorting the data according to requirement

ps_male = ps3_data1[ps3_data1.hsex==1]
ps_male_age=ps_male[(ps_male.age >= 25) & (ps_male.age <= 60)]
ps_male_age_wph=ps_male_age[ps_male_age.wph > 7]

In [13]:
ps_male_age_wph.describe()

year     hsex           age          educ           wph  \
count  57477.000000  57477.0  57477.000000  57097.000000  57477.000000   
mean    1986.635245      1.0     39.224247     13.529993     24.306034   
std        8.744894      0.0      9.579065      2.449510     25.154028   
min     1971.000000      1.0     25.000000      1.000000      7.000252   
25%     1979.000000      1.0     31.000000     12.000000     13.947624   
50%     1987.000000      1.0     38.000000     13.000000     19.905161   
75%     1994.000000      1.0     47.000000     16.000000     27.787226   
max     2002.000000      1.0     60.000000     17.000000   1717.330322   

              White         Black    Other_Race        lnwage    const  
count  57477.000000  57477.000000  57477.000000  57477.000000  57477.0  
mean       0.918907      0.056388      0.023035      3.010414      1.0  
std        0.272981      0.230671      0.150017      0.543891      0.0  
min        0.000000      0.000000      0.000000      1.945946      1.0  
25%        1.000000      0.000000      0.000000      2.635309      1.0  
50%        1.000000      0.000000      0.000000      2.990979      1.0  
75%        1.000000      0.000000      0.000000      3.324576      1.0  
max        1.000000      1.000000      1.000000      7.448526      1.0

In [14]:
ps_male_age_wph.columns

Index(['year', 'hsex', 'age', 'educ', 'wph', 'White', 'Black', 'Other_Race',
       'lnwage', 'const'],
      dtype='object')

In [15]:
ps_male_age_wph

year  hsex   age  educ         wph  White  Black  Other_Race  \
11161   1971   1.0  51.0  12.0   41.318916      1      0           0   
11164   1971   1.0  55.0   5.0   11.274115      1      0           0   
11166   1971   1.0  25.0  16.0   10.257995      1      0           0   
11173   1971   1.0  39.0  16.0   32.035599      1      0           0   
11175   1971   1.0  36.0  12.0   10.103716      1      0           0   
11192   1971   1.0  31.0  17.0   18.994255      1      0           0   
11196   1971   1.0  42.0  11.0    9.600762      0      1           0   
11198   1971   1.0  36.0  11.0   16.548191      1      0           0   
11199   1971   1.0  44.0   9.0   16.519394      1      0           0   
11202   1971   1.0  55.0   7.0   20.233009      1      0           0   
11206   1971   1.0  52.0  11.0   10.281672      1      0           0   
11209   1971   1.0  56.0   9.0   20.092363      1      0           0   
11213   1971   1.0  25.0  15.0   27.688356      1      0           0   
11214   1971   1.0  36.0  11.0   21.417620      1      0           0   
11222   1971   1.0  27.0  12.0   11.116825      1      0           0   
11223   1971   1.0  58.0   8.0    9.356791      1      0           0   
11227   1971   1.0  47.0  16.0   27.236746      1      0           0   
11228   1971   1.0  25.0  11.0   10.559178      1      0           0   
11230   1971   1.0  33.0  12.0   29.854012      1      0           0   
11231   1971   1.0  56.0  12.0   22.448587      1      0           0   
11233   1971   1.0  28.0  16.0    8.885546      1      0           0   
11234   1971   1.0  48.0   9.0   25.250536      1      0           0   
11237   1971   1.0  44.0  11.0   13.390574      1      0           0   
11243   1971   1.0  51.0  17.0   24.575472      1      0           0   
11244   1971   1.0  49.0  16.0   18.884144      1      0           0   
11245   1971   1.0  52.0  12.0   28.452671      1      0           0   
11246   1971   1.0  43.0  15.0   38.320095      1      0           0   
11248   1971   1.0  45.0  14.0   74.542671      1      0           0   
11249   1971   1.0  60.0  16.0   50.582527      1      0           0   
11252   1971   1.0  47.0  16.0   40.855114      1      0           0   
...      ...   ...   ...   ...         ...    ...    ...         ...   
123721  2002   1.0  50.0  14.0   26.248682      1      0           0   
123723  2002   1.0  26.0  13.0   27.244413      1      0           0   
123725  2002   1.0  41.0  12.0   16.117611      1      0           0   
123727  2002   1.0  35.0  12.0   28.967138      1      0           0   
123729  2002   1.0  38.0  17.0   25.656609      1      0           0   
123730  2002   1.0  27.0  11.0   24.388958      1      0           0   
123731  2002   1.0  26.0  12.0    9.117964      1      0           0   
123732  2002   1.0  46.0  16.0   44.527996      1      0           0   
123734  2002   1.0  29.0  12.0   21.820946      1      0           0   
123735  2002   1.0  34.0  16.0   73.533554      1      0           0   
123741  2002   1.0  37.0  14.0   15.314409      1      0           0   
123742  2002   1.0  31.0  12.0   18.838768      0      1           0   
123743  2002   1.0  59.0  14.0   10.361322      1      0           0   
123744  2002   1.0  36.0  17.0   43.982754      0      0           1   
123745  2002   1.0  43.0  14.0   43.103100      1      0           0   
123748  2002   1.0  44.0  12.0   39.544128      1      0           0   
123753  2002   1.0  42.0  11.0   16.555510      1      0           0   
123754  2002   1.0  43.0  14.0   23.706705      0      1           0   
123755  2002   1.0  31.0  12.0   27.074812      1      0           0   
123757  2002   1.0  41.0  16.0   25.367741      0      1           0   
123758  2002   1.0  28.0  14.0   46.447308      0      1           0   
123761  2002   1.0  53.0  16.0   48.201778      1      0           0   
123765  2002   1.0  49.0  12.0   12.578727      0      1           0   
123766  2002   1.0  29.0  13.0    8.319371      

# Creating new data sets by different years

In [16]:
ps_1971=ps_male_age_wph[ps_male_age_wph.year==1971]

In [17]:
ps_1980=ps_male_age_wph[ps_male_age_wph.year==1980]

In [18]:
ps_1990=ps_male_age_wph[ps_male_age_wph.year==1990]

In [19]:
ps_2000=ps_male_age_wph[ps_male_age_wph.year==2000]

# OLS output for different years

In [20]:
import statsmodels.api as sm

C:\Users\mmic\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


Year 1971

In [21]:
reg1=sm.OLS(endog=ps_1971['lnwage'], exog=ps_1971[['const','educ','age','Black','Other_Race']],missing='drop')

In [22]:
results1 = reg1.fit()

In [23]:
type (results1)
print(results1.summary())

                            OLS Regression Results                            
Dep. Variable:                 lnwage   R-squared:                       0.244
Model:                            OLS   Adj. R-squared:                  0.241
Method:                 Least Squares   F-statistic:                     110.7
Date:                Tue, 26 Sep 2017   Prob (F-statistic):           7.42e-82
Time:                        11:16:45   Log-Likelihood:                -728.06
No. Observations:                1380   AIC:                             1466.
Df Residuals:                    1375   BIC:                             1492.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.5510      0.073     21.382      0.0

Year 1980

In [24]:
reg2=sm.OLS(endog=ps_1980['lnwage'], exog=ps_1980[['const','educ','age','Black','Other_Race']],missing='drop')

In [25]:
results2 = reg2.fit()
type (results2)
print(results2.summary())

                            OLS Regression Results                            
Dep. Variable:                 lnwage   R-squared:                       0.169
Model:                            OLS   Adj. R-squared:                  0.167
Method:                 Least Squares   F-statistic:                     94.08
Date:                Tue, 26 Sep 2017   Prob (F-statistic):           6.41e-73
Time:                        11:16:45   Log-Likelihood:                -1148.4
No. Observations:                1856   AIC:                             2307.
Df Residuals:                    1851   BIC:                             2334.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.6131      0.075     21.590      0.0

Year 1990

In [26]:
reg3=sm.OLS(endog=ps_1990['lnwage'], exog=ps_1990[['const','educ','age','Black','Other_Race']],missing='drop')

In [27]:
results3 = reg3.fit()
type (results3)
print(results3.summary())

                            OLS Regression Results                            
Dep. Variable:                 lnwage   R-squared:                       0.217
Model:                            OLS   Adj. R-squared:                  0.216
Method:                 Least Squares   F-statistic:                     139.3
Date:                Tue, 26 Sep 2017   Prob (F-statistic):          3.67e-105
Time:                        11:16:45   Log-Likelihood:                -1393.9
No. Observations:                2013   AIC:                             2798.
Df Residuals:                    2008   BIC:                             2826.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.1186      0.084     13.312      0.0

Year 2000

In [28]:
reg4=sm.OLS(endog=ps_2000['lnwage'], exog=ps_2000[['const','educ','age','Black','Other_Race']],missing='drop')

In [29]:
results4 = reg4.fit()
type (results4)
print(results4.summary())

                            OLS Regression Results                            
Dep. Variable:                 lnwage   R-squared:                       0.207
Model:                            OLS   Adj. R-squared:                  0.205
Method:                 Least Squares   F-statistic:                     168.6
Date:                Tue, 26 Sep 2017   Prob (F-statistic):          1.75e-128
Time:                        11:16:45   Log-Likelihood:                -2081.4
No. Observations:                2595   AIC:                             4173.
Df Residuals:                    2590   BIC:                             4202.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.1611      0.080     14.436      0.0

Interpretation of education coefficient for different years by OLS

Given one year increase in the years of education of the household head, we expect the wage to rise by 6.69 percentage, 6.76 percentage, 9.76 percentage, and 10.92 percentage in years 1971, 1980,1990, and 2000 respectivley.

# Loglikelihood Optimization

# Year 1971

In [30]:
def loglik71(b):
    '''
    This function returns the loglikelihood value for given betas and sigma (b) for year 1971.
    '''
    y=ps_1971['lnwage']
    yhat=b[0]+b[1]*ps_1971['educ']+b[2]*ps_1971['age']+b[3]*ps_1971['Black']+b[4]*ps_1971['Other_Race']
    e=y-yhat
    LL = -(len(e)/2)*np.log(2*np.pi)-len(e)*np.log(b[5])-(1/(2*b[5]**2))*((e*e).sum())
    return -LL

In [31]:
# Here b[5] = sigma
b0=[2,0.1,0.02,0.06,0.1,0.1]

In [32]:
# Applying bounds=bnds for the parameters where bound for sigma is (0,np.inf)

bnds = ((-np.inf, np.inf),(-np.inf, np.inf), (-np.inf, np.inf),(-np.inf, np.inf), (-np.inf, np.inf), (0, np.inf))

In [33]:
results_SLSQP1 = opt.minimize(loglik71,b0,bounds=bnds, method='SLSQP')
print(results_SLSQP1)

     fun: 15995.242818855651
     jac: array([ 0.        ,  0.        ,  0.        , -0.00390625, -0.00146484,
        0.00146484])
 message: 'Optimization terminated successfully.'
    nfev: 170
     nit: 19
    njev: 19
  status: 0
 success: True
       x: array([  2.00000000e+00,  -1.71199106e+02,  -4.93293359e+02,
         8.75998335e+01,   3.92915666e+01,   2.26046431e+04])


In [34]:
results_BFGS1 = opt.minimize(loglik71,b0,bounds=bnds, method='L-BFGS-B',tol=1e-15)
print(results_BFGS1)

      fun: nan
 hess_inv: <6x6 LbfgsInvHessProduct with dtype=float64>
      jac: array([   0.        , -164.26492948,  748.25716183,  127.68060742,
         18.06280352,   34.44326921])
  message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
     nfev: 469
      nit: 19
   status: 2
  success: False
        x: array([ 2.        ,  0.05068645,  0.00814371,  0.05580784,  0.09932973,
        0.42053305])


C:\Users\mmic\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in log
  
C:\Users\mmic\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in double_scalars
  
C:\Users\mmic\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in double_scalars
  


In [35]:
results_NM1 = opt.minimize(loglik71,b0, method='Nelder-Mead',tol=1e-15)
print(results_NM1)

 final_simplex: (array([[ 1.55068243,  0.06689189,  0.01439381, -0.16373869,  0.03053483,
         0.40729411],
       [ 1.55068241,  0.06689189,  0.01439381, -0.16373862,  0.03053477,
         0.40729413],
       [ 1.55068242,  0.06689189,  0.01439381, -0.16373863,  0.03053475,
         0.40729413],
       [ 1.5506824 ,  0.06689189,  0.01439381, -0.16373866,  0.03053473,
         0.40729412],
       [ 1.55068241,  0.06689189,  0.01439381, -0.16373859,  0.03053475,
         0.40729413],
       [ 1.55068239,  0.06689189,  0.01439381, -0.16373856,  0.03053468,
         0.40729415],
       [ 1.55068241,  0.06689189,  0.01439381, -0.1637386 ,  0.03053464,
         0.40729414]]), array([ 728.52180621,  728.52180621,  728.52180621,  728.52180621,
        728.52180621,  728.52180621,  728.52180621]))
           fun: 728.52180620690001
       message: 'Maximum number of function evaluations has been exceeded.'
          nfev: 1201
           nit: 745
        status: 1
       success: False
   

# Year 1980

In [36]:
def loglik80(b):
    '''
    This function returns the loglikelihood value for given betas and sigma (b) for year 1980.
    '''
    y=ps_1980['lnwage']
    yhat=b[0]+b[1]*ps_1980['educ']+b[2]*ps_1980['age']+b[3]*ps_1980['Black']+b[4]*ps_1980['Other_Race']
    e=y-yhat
    LL = -(len(e)/2)*np.log(2*np.pi)-len(e)*np.log(b[5])-(1/(2*b[5]**2))*((e*e).sum())
    return -LL

In [37]:
results_SLSQP2 = opt.minimize(loglik80,b0,bounds=bnds, method='SLSQP')
print(results_SLSQP2)

     fun: 21668.607453399633
     jac: array([ 0.        ,  0.        ,  0.        , -0.00366211, -0.0012207 ,
        0.00341797])
 message: 'Optimization terminated successfully.'
    nfev: 161
     nit: 18
    njev: 18
  status: 0
 success: True
       x: array([  2.00000000e+00,  -2.32615419e+02,  -6.37483419e+02,
         6.65387443e+01,   2.89522934e+01,   2.90296660e+04])


In [38]:
results_BFGS2 = opt.minimize(loglik80,b0,bounds=bnds, method='L-BFGS-B',tol=1e-15)
print(results_BFGS2)

      fun: nan
 hess_inv: <6x6 LbfgsInvHessProduct with dtype=float64>
      jac: array([    0.        ,  3167.13947086, -1743.15125605,    -4.74365152,
          11.84303073,    36.16989943])
  message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
     nfev: 721
      nit: 30
   status: 2
  success: False
        x: array([ 2.        ,  0.04282668,  0.01087241, -0.13584097,  0.07702936,
        0.45556698])


C:\Users\mmic\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in log
  
C:\Users\mmic\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in double_scalars
  
C:\Users\mmic\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in double_scalars
  


In [39]:
results_NM2 = opt.minimize(loglik80,b0, method='Nelder-Mead',tol=1e-15)
print(results_NM2)

 final_simplex: (array([[ 1.61027294,  0.06770588,  0.01272869, -0.09456881, -0.02163746,
         0.44917999],
       [ 1.61027294,  0.06770588,  0.01272869, -0.09456881, -0.02163746,
         0.44917999],
       [ 1.61027294,  0.06770588,  0.01272869, -0.09456881, -0.02163746,
         0.44917999],
       [ 1.61027294,  0.06770588,  0.01272869, -0.09456881, -0.02163746,
         0.44917999],
       [ 1.61027294,  0.06770588,  0.01272869, -0.09456881, -0.02163746,
         0.44917999],
       [ 1.61027294,  0.06770588,  0.01272869, -0.09456881, -0.02163746,
         0.44917999],
       [ 1.61027294,  0.06770588,  0.01272869, -0.09456881, -0.02163746,
         0.44917999]]), array([ 1148.65611911,  1148.65611911,  1148.65611911,  1148.65611911,
        1148.65611911,  1148.65611911,  1148.65611911]))
           fun: 1148.6561191070671
       message: 'Maximum number of function evaluations has been exceeded.'
          nfev: 1201
           nit: 682
        status: 1
       success: Fa

# Year 1990

In [40]:
def loglik90(b):
    '''
    This function returns the loglikelihood value for given betas and sigma (b) for year 1990.
    '''
    y=ps_1990['lnwage']
    yhat=b[0]+b[1]*ps_1990['educ']+b[2]*ps_1990['age']+b[3]*ps_1990['Black']+b[4]*ps_1990['Other_Race']
    e=y-yhat
    LL = -(len(e)/2)*np.log(2*np.pi)-len(e)*np.log(b[5])-(1/(2*b[5]**2))*((e*e).sum())
    return -LL

In [41]:
results_SLSQP3 = opt.minimize(loglik90,b0,bounds=bnds, method='SLSQP')
print(results_SLSQP3)

     fun: 23788.53191444083
     jac: array([ 0.        ,  0.        ,  0.        , -0.00317383, -0.00073242,
        0.00024414])
 message: 'Optimization terminated successfully.'
    nfev: 165
     nit: 18
    njev: 18
  status: 0
 success: True
       x: array([  2.00000000e+00,  -2.77845818e+02,  -7.12583320e+02,
         5.51611627e+01,   1.67380986e+01,   3.22114618e+04])


In [42]:
results_BFGS3 = opt.minimize(loglik90,b0,bounds=bnds, method='L-BFGS-B',tol=1e-15)
print(results_BFGS3)

      fun: nan
 hess_inv: <6x6 LbfgsInvHessProduct with dtype=float64>
      jac: array([  0.00000000e+00,   1.21096846e+04,  -1.47015994e+03,
         1.08554855e+02,   1.39077201e+01,   1.14852355e+01])
  message: b'ABNORMAL_TERMINATION_IN_LNSRCH'
     nfev: 672
      nit: 26
   status: 2
  success: False
        x: array([ 2.        ,  0.02209948,  0.01704091,  0.0537477 ,  0.09909537,
        0.51755757])


C:\Users\mmic\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in log
  
C:\Users\mmic\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in double_scalars
  
C:\Users\mmic\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in double_scalars
  


In [43]:
results_NM3 = opt.minimize(loglik90,b0, method='Nelder-Mead',tol=1e-15)
print(results_NM3)

 final_simplex: (array([[ 1.11840719,  0.09756539,  0.01346719, -0.17203877, -0.05980211,
         0.48323804],
       [ 1.11840719,  0.09756539,  0.01346719, -0.17203879, -0.05980213,
         0.48323804],
       [ 1.11840719,  0.09756539,  0.01346719, -0.17203881, -0.05980215,
         0.48323804],
       [ 1.11840719,  0.09756539,  0.01346719, -0.17203881, -0.05980216,
         0.48323804],
       [ 1.11840719,  0.09756539,  0.01346719, -0.17203884, -0.05980218,
         0.48323804],
       [ 1.11840719,  0.09756539,  0.01346719, -0.17203885, -0.05980219,
         0.48323804],
       [ 1.11840719,  0.09756539,  0.01346719, -0.17203886, -0.05980221,
         0.48323804]]), array([ 1394.45831523,  1394.45831523,  1394.45831523,  1394.45831523,
        1394.45831523,  1394.45831523,  1394.45831523]))
           fun: 1394.4583152308287
       message: 'Maximum number of function evaluations has been exceeded.'
          nfev: 1200
           nit: 706
        status: 1
       success: Fa

# Year 2000

In [44]:
def loglik00(b):
    '''
    This function returns the loglikelihood value for given betas and sigma (b) for year 2000.
    '''
    y=ps_2000['lnwage']
    yhat=b[0]+b[1]*ps_2000['educ']+b[2]*ps_2000['age']+b[3]*ps_2000['Black']+b[4]*ps_2000['Other_Race']
    e=y-yhat
    LL = -(len(e)/2)*np.log(2*np.pi)-len(e)*np.log(b[5])-(1/(2*b[5]**2))*((e*e).sum())
    return -LL

In [45]:
results_SLSQP4 = opt.minimize(loglik00,b0,bounds=bnds, method='SLSQP')
print(results_SLSQP4)

     fun: 32343.932554172494
     jac: array([ 0.        ,  0.        ,  0.        , -0.00292969, -0.00195312,
        0.00024414])
 message: 'Optimization terminated successfully.'
    nfev: 168
     nit: 19
    njev: 19
  status: 0
 success: True
       x: array([  2.00000000e+00,  -3.46494445e+02,  -9.28356145e+02,
         7.25415963e+01,   4.57813106e+01,   4.34467573e+04])


In [46]:
results_BFGS4 = opt.minimize(loglik00,b0,bounds=bnds, method='L-BFGS-B',tol=1e-15)
print(results_BFGS4)

      fun: 2162.505136314634
 hess_inv: <6x6 LbfgsInvHessProduct with dtype=float64>
      jac: array([  0.00000000e+00,   7.92387436e+02,   3.02240715e+03,
        -6.54667929e+00,   2.11662154e+01,  -6.53562893e-01])
  message: b'CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH'
     nfev: 973
      nit: 40
   status: 0
  success: True
        x: array([ 2.        ,  0.0723178 ,  0.00359789, -0.31838234, -0.02218935,
        0.54319361])


In [47]:
results_NM4 = opt.minimize(loglik00,b0, method='Nelder-Mead',tol=1e-15)
print(results_NM4)

 final_simplex: (array([[ 1.16381484,  0.10915288,  0.01094126, -0.26323987, -0.03960205,
         0.5313921 ],
       [ 1.16381484,  0.10915288,  0.01094126, -0.26323987, -0.03960205,
         0.5313921 ],
       [ 1.16381484,  0.10915288,  0.01094126, -0.26323987, -0.03960205,
         0.5313921 ],
       [ 1.16381484,  0.10915288,  0.01094126, -0.26323987, -0.03960205,
         0.5313921 ],
       [ 1.16381484,  0.10915288,  0.01094126, -0.26323987, -0.03960205,
         0.5313921 ],
       [ 1.16381484,  0.10915288,  0.01094126, -0.26323987, -0.03960205,
         0.5313921 ],
       [ 1.16381484,  0.10915288,  0.01094126, -0.26323987, -0.03960205,
         0.5313921 ]]), array([ 2104.77503873,  2104.77503873,  2104.77503873,  2104.77503873,
        2104.77503873,  2104.77503873,  2104.77503873]))
           fun: 2104.7750387273677
       message: 'Optimization terminated successfully.'
          nfev: 1157
           nit: 608
        status: 0
       success: True
             x: a

# Interpretation of education coefficient

Using Nelder-Mead Method

Given one year increase in the years of education of the household head, we expect the wage to rise by 6.69 percentage, 6.77 percentage, 9.76 percentage, and 10.92 percentage in years 1971, 1980,1990, and 2000 respectivley.

* Results using other two methods (SLSQP and L-BFGS-B) are not consistent with the OLS result. So, I didn't interpret those results.